Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MiniOrdersTable
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
