Resources:
  OrderManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: MiniOrdersTable
      Environment:
        Variables:
          ORDERS_TABLE: MiniOrdersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: get
